DROP USER 'root'@'localhost';
CREATE USER '#MYSQL_ROOT_USER#'@'#MYSQL_ROOT_HOST#' IDENTIFIED BY '#MYSQL_ROOT_PASSWORD#';
GRANT ALL PRIVILEGES ON *.* TO '#MYSQL_ROOT_USER#'@'#MYSQL_ROOT_HOST#' WITH GRANT OPTION;
GRANT RELOAD,PROCESS ON *.* TO '#MYSQL_ROOT_USER#'@'#MYSQL_ROOT_HOST#';
FLUSH PRIVILEGES;
