version: "3.3"

networks:
  nominal:
    external: true

services:

  postifx:
    image: sergiocabral/postfix
    container_name: ${PostifxName}
    restart: unless-stopped
    hostname: ${PostifxHostname}
    networks:
      - nominal
    ports:
      - ${PostifxPort}:25
    volumes:
      - ${HostDirectoryConfiguration}/${PostifxName}/templates:/etc/postfix.templates
      - ${HostDirectoryData}/${PostifxName}/conf:/etc/postfix.conf
      - ${HostDirectoryTemporary}/${PostifxName}/log:/var/log
