# Infraestrutura para o Cardapiou

version: "3.3"

networks:
  network-nominal:
    driver: bridge
    
services:


  squid:
    env_file: ./.env
    build:
      context: ../../images/squid/
    image: squid
    container_name: ${SquidName}
    restart: unless-stopped
    networks:
      - network-nominal
    ports:
      - 805:805
    volumes:
      - ${HostDirectoryConfiguration}/${SquidName}/templates:/etc/squid/templates
      - ${HostDirectoryData}/${SquidName}/passwd:/etc/squid/passwd
      - ${HostDirectoryData}/${SquidName}/conf:/etc/squid/conf
      - ${HostDirectoryTemporary}/${SquidName}/cache:/var/spool/squid
      - ${HostDirectoryTemporary}/${SquidName}/log:/var/log/squid
    environment:
      - SQUID_AUTH_USER=${SquidUser}
      - SQUID_AUTH_PASS=${SquidPass}
