# Infraestrutura para o Cardapiou

version: "3.3"

networks:
  network-nominal:
    driver: bridge
    
services:

  portainer:
    env_file: ./.env
    container_name: ${PortainerName}
    image: portainer/portainer:latest
    restart: unless-stopped
    networks:
      - network-nominal
    expose:
      - ${PortainerPort}
    volumes:
      - ${HostDirectoryData}/${PortainerName}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  netdata:
    env_file: ./.env
    container_name: ${NetdataName}
    image: netdata/netdata:latest
    restart: unless-stopped
    networks:
      - network-nominal
    expose:
      - ${NetdataPort}
    volumes:
      - ${HostDirectoryTemporary}/${NetdataName}/cache:/var/cache/netdata
      - ${HostDirectoryTemporary}/${NetdataName}/log:/var/log/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_USR=root
      - VIRTUALIZATION=${VIRTUALIZATION}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

  teamcity:
    env_file: ./.env
    container_name: ${TeamcityName}
    image: jetbrains/teamcity-server:latest
    restart: unless-stopped
    networks:
      - network-nominal
    expose:
      - ${TeamcityPort}
    volumes:
      - ${HostDirectoryData}/${TeamcityName}/data:/data/teamcity_server/datadir
      - ${HostDirectoryTemporary}/${TeamcityName}/log:/opt/teamcity/logs

  nginx:
    env_file: ./.env
    build:
      context: ../../images/nginx-certbot/
    image: nginx-certbot
    container_name: ${NginxName}
    restart: unless-stopped
    networks:
      - network-nominal
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HostDirectoryConfiguration}/${NginxName}/templates:/etc/nginx/templates
      - ${HostDirectoryConfiguration}/${NginxName}/html:/usr/share/nginx/html
      - ${HostDirectoryConfiguration}/${NginxName}/auth:/etc/nginx/auth
      - ${HostDirectoryData}/${NginxName}/conf.d:/etc/nginx/conf.d
      - ${HostDirectoryData}/${NginxName}/letsencrypt/archive:/etc/letsencrypt/archive
      - ${HostDirectoryData}/${NginxName}/letsencrypt/live:/etc/letsencrypt/live
      - ${HostDirectoryTemporary}/${NginxName}/log:/var/log/nginx
      - ${HostDirectoryTemporary}/${NginxName}/log:/var/log/letsencrypt
    environment:
      - CERTIFICATE_EMAIL=${ComputerName}@${ComputerDomain}
      - CERTIFICATE_DOMAIN_1=${ComputerName}.${ComputerDomain}
      - CERTIFICATE_DOMAIN_2=${PortainerDomain}.${ComputerDomain}
      - CERTIFICATE_DOMAIN_3=${TeamcityDomain}.${ComputerDomain}
      - CERTIFICATE_DOMAIN_4=${NetdataDomain}.${ComputerDomain}
    depends_on:
      - portainer
      - netdata
      - teamcity
