version: "3.3"

networks:
  nominal:
    external: true
    
services:

  proxy:
    image: sergiocabral/squid
    container_name: ${ProxyName}
    restart: unless-stopped
    networks:
      - nominal
    ports:
      - ${ProxyPort}:3128
    volumes:
      - ${HostDirectoryConfiguration}/${ProxyName}/templates:/etc/squid.templates
      - ${HostDirectoryData}/${ProxyName}/conf:/etc/squid.conf
      - ${HostDirectoryTemporary}/${ProxyName}/log:/var/log/squid
    environment:
      - SQUID_USERS=${SQUID_USERS}
      - SQUID_LOGIN_MESSAGE=${SQUID_LOGIN_MESSAGE}
      - SQUID_ALLOW_UNSECURE=${SQUID_ALLOW_UNSECURE}
