version: "3.3"

networks:
  nominal:
    driver: bridge
    
services:

  proxy:
    image: sergiocabral/squid
    container_name: ${ProxyName}
    restart: unless-stopped
    networks:
      - nominal
    ports:
      - ${ProxyPort}:3128
    volumes:
      - ${HostDirectoryConfiguration}/${ProxyName}/templates:/etc/squid.templates
      - ${HostDirectoryData}/${ProxyName}/conf:/etc/squid.conf
      - ${HostDirectoryTemporary}/${ProxyName}/log:/var/log/squid
    environment:
      - SQUID_USERS=${ProxyUsers}
      - SQUID_LOGIN_MESSAGE=${ProxyLoginMessage}
      - SQUID_ALLOW_UNSECURE=${ProxyAllowUnsecure}
