# Infraestrutura para o Cardapiou

version: "3.3"

services:

  certificates-ssl:
    build:
      dockerfile: .dockerfile
      context: ./images/certificates-ssl/
    image: certificates-ssl
    container_name: certificates-ssl
    environment:
      CERTIFICATE_EMAIL: "nominaler@cabral.srv.br"
      CERTIFICATE_DOMAINS: "nominaler.cabral.srv.br,docker.cabral.srv.br,teamcity.cabral.srv.br+docker.cabral.srv.br+teamcity.cabral.srv.br"
    ports:
      - 80:80
    volumes:
      - ${HostDirectoryData}certificates-ssl:/etc/letsencrypt/archive
    networks: 
    - network-nominal

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HostDirectoryConfiguration}nginx/templates:/etc/nginx/templates
      - ${HostDirectoryConfiguration}nginx/html:/usr/share/nginx/html
      - ${HostDirectoryTemporary}nginx/conf.d:/etc/nginx/conf.d
      - ${HostDirectoryTemporary}nginx/log:/var/log/nginx
      - ${HostDirectoryData}certificates-ssl:/etc/nginx/certs
    env_file: 
      - ./.env
    networks:
      - network-nominal
    restart: unless-stopped
    depends_on: 
      - certificates-ssl

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    expose:
      - 9000
    volumes:
      - ${HostDirectoryData}portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - ./.env
    networks:
      - network-nominal
    restart: unless-stopped
    depends_on: 
      - nginx
    
networks:
  network-nominal:
    driver: bridge