# Infraestrutura para o Cardapiou

version: "3.3"

services:

  portainer:
    env_file: ./.env
    container_name: ${PortainerName}
    image: portainer/portainer:latest
    expose:
      - ${PortainerPort}
    volumes:
      - ${HostDirectoryData}/${PortainerName}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-nominal
    restart: unless-stopped

  teamcity:
    env_file: ./.env
    container_name: ${TeamcityName}
    image: jetbrains/teamcity-server:latest
    expose:
      - ${TeamcityPort}
    volumes:
      - ${HostDirectoryData}/${TeamcityName}/data:/data/teamcity_server/datadir
      - ${HostDirectoryTemporary}/${TeamcityName}/log:/opt/teamcity/logs
    networks:
      - network-nominal
    restart: unless-stopped

  nginx:
    env_file: ./.env
    build:
      context: ./images/nginx-certbot/
    image: nginx-certbot
    container_name: ${NginxName}
    environment:
      CERTIFICATE_EMAIL: "${ComputerName}@${ComputerDomain}"
      CERTIFICATE_DOMAINS: "${ComputerName}.${ComputerDomain} + docker.${ComputerDomain} + teamcity.${ComputerDomain}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HostDirectoryConfiguration}/${NginxName}/templates:/etc/nginx/templates
      - ${HostDirectoryConfiguration}/${NginxName}/html:/usr/share/nginx/html
      - ${HostDirectoryData}/${NginxName}/conf.d:/etc/nginx/conf.d
      - ${HostDirectoryData}/${NginxName}/letsencrypt/archive:/etc/letsencrypt/archive
      - ${HostDirectoryData}/${NginxName}/letsencrypt/live:/etc/letsencrypt/live
      - ${HostDirectoryTemporary}/${NginxName}/log:/var/log/nginx
      - ${HostDirectoryTemporary}/${NginxName}/log:/var/log/letsencrypt
    networks:
      - network-nominal
    restart: unless-stopped
    
networks:
  network-nominal:
    driver: bridge