# Infraestrutura para o Cardapiou

version: "3.3"

services:

  nginx:
    build:
      context: ./images/nginx-certbot/
    image: nginx-certbot
    container_name: nginx
    environment:
      CERTIFICATE_EMAIL: "${ComputerName}@${DomainSuffix}"
      CERTIFICATE_DOMAINS: "${ComputerName}.${DomainSuffix} + docker.${DomainSuffix} + teamcity.${DomainSuffix}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HostDirectoryConfiguration}nginx/templates:/etc/nginx/templates
      - ${HostDirectoryConfiguration}nginx/html:/usr/share/nginx/html
      - ${HostDirectoryData}nginx/conf.d:/etc/nginx/conf.d
      - ${HostDirectoryTemporary}nginx/log:/var/log/nginx
      - ${HostDirectoryData}letsencrypt/archive:/etc/letsencrypt/archive
      - ${HostDirectoryData}letsencrypt/live:/etc/letsencrypt/live
      - ${HostDirectoryTemporary}letsencrypt/log:/var/log/letsencrypt
    env_file: 
      - ./.env
    networks:
      - network-nominal
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    expose:
      - 9000
    volumes:
      - ${HostDirectoryData}portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - ./.env
    networks:
      - network-nominal
    restart: unless-stopped
    depends_on: 
      - nginx
    
networks:
  network-nominal:
    driver: bridge